- type: job
  id: NFPirate
  name: job-name-nf-pirate
  description: job-description-nf-pirate
  playTimeTracker: JobPirate
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 43200 # frontier: 24 hrs / 4 shifts | CS: 12 hours / 2 shifts
    - !type:RoleTimeRequirement
      role: JobPirate
      time: 3600 # CS: 1 hour
#    - !type:DepartmentTimeRequirement # CS: swaps the playtime requirement to literally just be an hour of the role itself.
#      department: Security
#      time: 10800 # 3 hrs
  startingGear: NFPirateGear
  alwaysUseSpawner: true
  hideConsoleVisibility: true
  canBeAntag: true
  consoleAdjustable: false
  icon: "JobIconNFPirate"
  supervisors: job-supervisors-nf-pirate
  weight: 20
  displayWeight: 20
  setPreference: true
  newPlayerMessage: false
  access:
  - Pirate
  - BlackMarket
  accessGroups:
  - GeneralAccess
  special:
  - !type:AddComponentSpecial
    components:
#    - type: AutoPirate
    - type: SpecialSectorStationRecord # must be given on spawn
      recordGeneration: FalseRecord
    - type: DisableSuitSensors
    - type: IsPirate
  - !type:AddRpiJobModifierSpecial
    modifiersToAdd:
    - rpiJobModifierPirate
  - !type:AddImplantSpecial
    implants: [ FreelanceTrackingImplant ]
  - !type:GiveItemOnHolidaySpecial # Even pirates get a piece of cake.
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift

- type: startingGear
  id: NFPirateGear
  equipment:
    belt: ClothingBeltUtility
    pocket1: BasePirateUplinkPirateCrew
  storage:
    back:
    - AppraisalTool
    - ComputerIFFFlatpack

- type: chameleonOutfit
  id: NFPirateChameleonOutfit
  job: NFPirate

- type: roleLoadout
  id: JobNFPirate
  groups:
  - NFPirateHead
#  - NFPirateNeck
  - ContractorNeck #Coyote: Pirate Loadout Expansion
  - NFPirateJumpsuit
#  - NFPirateGloves
  - MercenaryGloves #Coyote: Pirate Loadout Expansion
  - ContractorBackpack
  - NFPirateForcedOuterClothing
  - MercenaryOuterClothing #Coyote: Pirate Loadout Expansion
  - NFPirateShoes
  - NFPirateFace
  - MercenaryGlasses #Coyote: Pirate Loadout Expansion
  - MercenaryBelt #Coyote: Pirate Loadout Expansion
  - NFPirateEars
  - PirateEncryptionKey # Coyote: Pirates get comm keys
  - ContractorBoxSurvival
  - SmugglerPDA
  - ContractorWallet
  - PirateBackpackItems
  - ContractorHandItems
  - ContractorInstruments # Coyote
  - NFSpeciesSpecific
  canCustomizeName: true # pseudonym?
