- type: flarpiSettings
  id: FlarpiSettings_Default
  pointsPerFlarpi: 1000
  flarpiCurrencyPrototype: Doubloon
  flarpiName: freelancer
  baseFlarpi: 5
  linearFlarpiIncrease: 2
  nearbyRadius: 25
  freelancerCountMode: Nearby
  freelancerCalcMode: Linear
  maxFreelancersConsidered: 10
  nfsdCountMode: Nope
  nfsdCalcMode: Nope

- type: flarpiSettings
  id: FlarpiSettings_NFSD
  flarpiCurrencyPrototype: FrontierUplinkCoin
  pointsPerFlarpi: 1000
  flarpiName: nfsd
  baseFlarpi: 5
  linearFlarpiIncrease: 2
  nearbyRadius: 25
  freelancerCountMode: Online
  freelancerCalcMode: Linear
  maxFreelancersConsidered: 5
  nfsdCountMode: Online
  nfsdCalcMode: Linear

