- type: job
  id: SecurityGuard
  name: job-name-security-guard
  description: job-description-security-guard
  playTimeTracker: JobSecurityGuard
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 43200 # 12 hours
  - !type:DepartmentTimeRequirement
    department: Security
    time: 21600 # 6 hours
  startingGear: SecurityGuardGear
  alwaysUseSpawner: true
  icon: "JobIconSecurityGuard"
  supervisors: job-supervisors-guard
  weight: 80
  displayWeight: 20 # Second from the bottom
  canBeAntag: false
  accessGroups:
  - GeneralNfsdAccess
  access:
  - Security
  - Brig
  - Maintenance
  - Service
  - External
  - Mercenary
  - Captain
  - Frontier
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, TrackingImplant ]
  - !type:GiveItemOnHolidaySpecial
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift

- type: startingGear
  id: SecurityGuardGear
  equipment:
    eyes: ClothingEyesGlassesSecurity # CS: ClothingEyesGlassesSunglasses < ClothingEyesGlassesSecurity
    pocket1: NFWeaponPistolUniversalNfsdLessLethal
    pocket2: CSMagazinePistol40 # CS: NFMagazineHighCapacityPistol35 < CSMagazinePistol40
  storage:
    back:
    - EncryptionKeyService
    - EncryptionKeySecurity
    - EncryptionKeyNfsd
    - Flash
    - CSMagazinePistol40 # CS: NFMagazineHighCapacityPistol35 < CSMagazinePistol40
    - CSMagazinePistol40Rubber # CS: NFMagazineHighCapacityPistol35Rubber < CSMagazinePistol40Rubber
    - ShipVoucherFrontierGuard

- type: chameleonOutfit
  id: SecurityGuardChameleonOutfit
  job: SecurityGuard
  hasMindShield: true
  equipment:
    head: ClothingHeadHatBeretSecurity
    mask: ClothingMaskGasSecurity
    gloves: ClothingHandsGlovesColorBlack
