using Content.Shared.Humanoid;
using Content.Shared.Humanoid.Markings;
using Content.Shared.Humanoid.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.Utility;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;
using System.Numerics;
using System.Linq;
using static Robust.Client.UserInterface.Controls.BoxContainer;

namespace Content.Client.Humanoid;

[GenerateTypedNameReferences]
public sealed partial class MarkingPicker : Control
{
    [Dependency] private readonly MarkingManager _markingManager = default!;
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
    [Dependency] private readonly IEntityManager _entityManager = default!;

    private readonly SpriteSystem _sprite;

    public Action<MarkingSet>? OnMarkingAdded;
    public Action<MarkingSet>? OnMarkingRemoved;
    public Action<MarkingSet>? OnMarkingDataChanged;
    public Action<MarkingSet>? OnMarkingRankChange;
    public Action<HumanoidLegStyle>? OnLegStyleChanged;

    private List<Color> _currentMarkingColors = new();
    private List<float> _currentMarkingGlow = new();
    // Coyote Start
    private float _currentMarkingScale = 1.0f;
    private float _currentMarkingOffsetX;
    private float _currentMarkingOffsetY;
    // Coyote End

    private ItemList.Item? _selectedMarking;
    private ItemList.Item? _selectedUnusedMarking;
    private MarkingCategories _selectedMarkingCategory = MarkingCategories.Chest;

    private MarkingSet _currentMarkings = new();

    private List<MarkingCategories> _markingCategories = Enum.GetValues<MarkingCategories>().ToList();

    private string _currentSpecies = SharedHumanoidAppearanceSystem.DefaultSpecies;
    private Sex _currentSex = Sex.Unsexed;
    public Color CurrentSkinColor = Color.White;
    public Color CurrentEyeColor = Color.Black;
    public Marking? HairMarking;
    public Marking? FacialHairMarking;
    public HumanoidLegStyle CurrentLegStyle = HumanoidLegStyle.Plantigrade;

    private readonly HashSet<HumanoidLegStyle> _availableLegStyles = new()
    {
        HumanoidLegStyle.Plantigrade,
        HumanoidLegStyle.Digitigrade,
    };

    private readonly HashSet<MarkingCategories> _ignoreCategories = new();

    public string IgnoreCategories
    {
        get => string.Join(',', _ignoreCategories);
        set
        {
            _ignoreCategories.Clear();
            var split = value.Split(',');
            foreach (var category in split)
            {
                if (!Enum.TryParse(category, out MarkingCategories categoryParse))
                {
                    continue;
                }

                _ignoreCategories.Add(categoryParse);
            }

            SetupCategoryButtons();
        }
    }

    public bool Forced { get; set; }

    private bool _ignoreSpecies;

    public bool IgnoreSpecies
    {
        get => _ignoreSpecies;
        set
        {
            _ignoreSpecies = value;
            Populate(CMarkingSearch.Text);
        }
    }

    public void SetData(
        List<Marking> newMarkings,
        string species,
        Sex sex,
        Color skinColor,
        Color eyeColor,
        HumanoidLegStyle legStyle
    )
    {
        var pointsProto = _prototypeManager
            .Index<SpeciesPrototype>(species).MarkingPoints;
        _currentMarkings = new(newMarkings, pointsProto, _markingManager);

        if (!IgnoreSpecies)
        {
            _currentMarkings.EnsureSpecies(species, skinColor, _markingManager); // should be validated server-side but it can't hurt
        }

        _currentSpecies = species;
        _currentSex = sex;
        CurrentSkinColor = skinColor;
        CurrentEyeColor = eyeColor;

        CMarkingLegStyle.Clear();
        CurrentLegStyle = legStyle;
        if (!_availableLegStyles.Contains(legStyle))
            CurrentLegStyle = HumanoidLegStyle.Plantigrade;

        Populate(CMarkingSearch.Text);
        PopulateUsed();
    }

    public void SetData(MarkingSet set, string species, Sex sex, Color skinColor, Color eyeColor)
    {
        _currentMarkings = set;

        if (!IgnoreSpecies)
        {
            _currentMarkings.EnsureSpecies(species, skinColor, _markingManager); // should be validated server-side but it can't hurt
        }

        _currentSpecies = species;
        _currentSex = sex;
        CurrentSkinColor = skinColor;
        CurrentEyeColor = eyeColor;

        Populate(CMarkingSearch.Text);
        PopulateUsed();
    }

    public void SetSkinColor(Color color) => CurrentSkinColor = color;
    public void SetEyeColor(Color color) => CurrentEyeColor = color;

    public MarkingPicker()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _sprite = _entityManager.System<SpriteSystem>();

        // Subscribe to consent changes to refresh categories
        CMarkingCategoryButton.OnItemSelected += OnCategoryChange;
        CMarkingsUnused.OnItemSelected += item =>
            _selectedUnusedMarking = CMarkingsUnused[item.ItemIndex];

        CMarkingAdd.OnPressed += _ =>
            MarkingAdd();

        CMarkingsUsed.OnItemSelected += OnUsedMarkingSelected;

        CMarkingLegStyle.OnItemSelected += OnChangedLegStyle;

        CMarkingRemove.OnPressed += _ =>
            MarkingRemove();

        CMarkingRankUp.OnPressed += _ => SwapMarkingUp();
        CMarkingRankDown.OnPressed += _ => SwapMarkingDown();

        CanPutOnToggle.OnToggled += x => SetCanToggle(x.Pressed);
        CanPutOnByOtherToggle.OnToggled += x => SetOtherCanToggle(x.Pressed);
        HideTogglePopupToggle.OnToggled += x => SetHideTogglePopup(x.Pressed);
        StartVisibleToggle.OnToggled += x => SetVisible(x.Pressed);

        CustomNameTextEdit.OnTextChanged += x => SetCustomText();
        PutOnTextEdit.OnTextChanged += x => SetCustomText();
        TakeOffTextEdit.OnTextChanged += x => SetCustomText();
        PutOnOtherTextEdit.OnTextChanged += x => SetCustomText();
        TakeOffOtherTextEdit.OnTextChanged += x => SetCustomText();

        SampleButton.OnPressed += _ => ToggleSample();

        CMarkingSearch.OnTextChanged += args => Populate(args.Text);
    }

    private void SetupCategoryButtons()
    {
        CMarkingCategoryButton.Clear();

        var validCategories = new List<MarkingCategories>();
        for (var i = 0; i < _markingCategories.Count; i++)
        {
            var category = _markingCategories[i];
            var markings = GetMarkings(category);

            // Check if the category should be ignored
            if (_ignoreCategories.Contains(category) || markings.Count == 0)
            {
                continue;
            }

            validCategories.Add(category);
            CMarkingCategoryButton.AddItem(Loc.GetString($"markings-category-{category.ToString()}"), i);
        }

        if (validCategories.Contains(_selectedMarkingCategory))
        {
            CMarkingCategoryButton.SelectId(_markingCategories.IndexOf(_selectedMarkingCategory));
        }
        else if (validCategories.Count > 0)
        {
            _selectedMarkingCategory = validCategories[0];
        }
        else
        {
            _selectedMarkingCategory = MarkingCategories.Chest;
        }
    }

    private void SetupLegStyleButtons()
    {
        CMarkingLegStyle.Clear();

        foreach (var legStyle in _availableLegStyles)
        {
            CMarkingLegStyle.AddItem(Loc.GetString($"humanoid-leg-style-{legStyle.ToString()}"), (int)legStyle);
        }

        CMarkingLegStyle.SelectId((int)CurrentLegStyle);
    }

    private string GetMarkingName(MarkingPrototype marking) => Loc.GetString($"marking-{marking.ID}");

    private List<string> GetMarkingStateNames(MarkingPrototype marking)
    {
        List<string> result = new();
        foreach (var markingState in marking.Sprites)
        {
            switch (markingState)
            {
                case SpriteSpecifier.Rsi rsi:
                    result.Add(Loc.GetString($"marking-{marking.ID}-{rsi.RsiState}"));
                    break;
                case SpriteSpecifier.Texture texture:
                    result.Add(Loc.GetString($"marking-{marking.ID}-{texture.TexturePath.Filename}"));
                    break;
            }
        }

        return result;
    }

    private IReadOnlyDictionary<string, MarkingPrototype> GetMarkings(MarkingCategories category)
    {
        return IgnoreSpecies
            ? _markingManager.MarkingsByCategoryAndSex(category, _currentSex)
            : _markingManager.MarkingsByCategoryAndSpeciesAndSex(category, _currentSpecies, _currentSex);
    }

    public void Populate(string filter)
    {
        SetupCategoryButtons();
        SetupLegStyleButtons();

        CMarkingsUnused.Clear();
        _selectedUnusedMarking = null;

        IOrderedEnumerable<MarkingPrototype> sortedMarkings = GetMarkings(_selectedMarkingCategory)
            .Values.Where(m =>
                !m.Hidden
                && (m.ID.ToLower()
                        .Contains(filter.ToLower())
                    || GetMarkingName(m)
                        .ToLower()
                        .Contains(filter.ToLower())))
            .OrderBy(p => Loc.GetString(GetMarkingName(p)));

        foreach (var marking in sortedMarkings)
        {
            if (_currentMarkings.TryGetMarking(_selectedMarkingCategory, marking.ID, out _))
            {
                continue;
            }

            var item = CMarkingsUnused.AddItem($"{GetMarkingName(marking)}", _sprite.Frame0(marking.Sprites[0]));
            item.Metadata = marking;
        }

        CMarkingPoints.Visible = _currentMarkings.PointsLeft(_selectedMarkingCategory) != -1;
    }

    // Populate the used marking list. Returns a list of markings that weren't
    // valid to add to the marking list.
    public void PopulateUsed()
    {
        CMarkingsUsed.Clear();
        MarkingData.Visible = false;
        CMarkingColors.Visible = false;
        _selectedMarking = null;

        SampleBox.Visible = false;
        SampleButton.Visible = false;
        SampleButton.Text = Loc.GetString("marking-show-sample-text");

        if (!IgnoreSpecies)
        {
            _currentMarkings.EnsureSpecies(_currentSpecies, null, _markingManager);
        }

        // walk backwards through the list for visual purposes
        foreach (var marking in _currentMarkings.GetReverseEnumerator(_selectedMarkingCategory))
        {
            if (!_markingManager.TryGetMarking(marking, out var newMarking))
            {
                continue;
            }

            var text = Loc.GetString(marking.Forced ? "marking-used-forced" : "marking-used", ("marking-name", $"{GetMarkingName(newMarking)}"),
                ("marking-category", Loc.GetString($"markings-category-{newMarking.MarkingCategory}")));

            var item = new ItemList.Item(CMarkingsUsed)
            {
                Text = text,
                Icon = _sprite.Frame0(newMarking.Sprites[0]),
                Selectable = true,
                Metadata = newMarking,
                IconModulate = marking.MarkingColors[0]
            };

            CMarkingsUsed.Add(item);
        }

        // since all the points have been processed, update the points visually
        UpdatePoints();
    }

    private void SwapMarkingUp()
    {
        if (_selectedMarking == null)
        {
            return;
        }

        var i = CMarkingsUsed.IndexOf(_selectedMarking);
        if (ShiftMarkingRank(i, -1))
        {
            OnMarkingRankChange?.Invoke(_currentMarkings);
        }
    }

    private void SwapMarkingDown()
    {
        if (_selectedMarking == null)
        {
            return;
        }

        var i = CMarkingsUsed.IndexOf(_selectedMarking);
        if (ShiftMarkingRank(i, 1))
        {
            OnMarkingRankChange?.Invoke(_currentMarkings);
        }
    }

    private bool ShiftMarkingRank(int src, int places)
    {
        if (src + places >= CMarkingsUsed.Count || src + places < 0)
        {
            return false;
        }

        var visualDest = src + places; // what it would visually look like
        var visualTemp = CMarkingsUsed[visualDest];
        CMarkingsUsed[visualDest] = CMarkingsUsed[src];
        CMarkingsUsed[src] = visualTemp;

        switch (places)
        {
            // i.e., we're going down in rank
            case < 0:
                _currentMarkings.ShiftRankDownFromEnd(_selectedMarkingCategory, src);
                break;
            // i.e., we're going up in rank
            case > 0:
                _currentMarkings.ShiftRankUpFromEnd(_selectedMarkingCategory, src);
                break;
            // do nothing?
            // ReSharper disable once RedundantEmptySwitchSection
            default:
                break;
        }

        return true;
    }



    // repopulate in case markings are restricted,
    // and also filter out any markings that are now invalid
    // attempt to preserve any existing markings as well:
    // it would be frustrating to otherwise have all markings
    // cleared, imo
    public void SetSpecies(string species)
    {
        _currentSpecies = species;
        var markingList = _currentMarkings.GetForwardEnumerator().ToList();

        var speciesPrototype = _prototypeManager.Index<SpeciesPrototype>(species);

        _currentMarkings = new(markingList, speciesPrototype.MarkingPoints, _markingManager, _prototypeManager);
        _currentMarkings.EnsureSpecies(species, null, _markingManager);
        _currentMarkings.EnsureSexes(_currentSex, _markingManager);

        Populate(CMarkingSearch.Text);
        PopulateUsed();
    }

    public void SetSex(Sex sex)
    {
        _currentSex = sex;
        var markingList = _currentMarkings.GetForwardEnumerator().ToList();

        var speciesPrototype = _prototypeManager.Index<SpeciesPrototype>(_currentSpecies);

        _currentMarkings = new(markingList, speciesPrototype.MarkingPoints, _markingManager, _prototypeManager);
        _currentMarkings.EnsureSpecies(_currentSpecies, null, _markingManager);
        _currentMarkings.EnsureSexes(_currentSex, _markingManager);

        Populate(CMarkingSearch.Text);
        PopulateUsed();
    }

    private void UpdatePoints()
    {
        var count = _currentMarkings.PointsLeft(_selectedMarkingCategory);
        if (count > -1)
        {
            CMarkingPoints.Text = Loc.GetString("marking-points-remaining", ("points", count));
        }
    }

    private void OnCategoryChange(OptionButton.ItemSelectedEventArgs category)
    {
        CMarkingCategoryButton.SelectId(category.Id);
        _selectedMarkingCategory = _markingCategories[category.Id];
        Populate(CMarkingSearch.Text);
        PopulateUsed();
        UpdatePoints();
    }

    // TODO: This should be using ColorSelectorSliders once that's merged, so
    private void OnUsedMarkingSelected(ItemList.ItemListSelectedEventArgs item)
    {
        _selectedMarking = CMarkingsUsed[item.ItemIndex];
        var prototype = (MarkingPrototype)_selectedMarking.Metadata!;
        int markingIndex = _currentMarkings.FindIndexOf(_selectedMarkingCategory, prototype.ID);

        if (markingIndex < 0) return;

        var marking = _currentMarkings.Markings[_selectedMarkingCategory][markingIndex];

        if (prototype.ForcedColoring)
        {
            CMarkingColors.Visible = false;

            return;
        }

        var stateNames = GetMarkingStateNames(prototype);
        _currentMarkingColors.Clear();
        _currentMarkingGlow.Clear();
        CMarkingColors.DisposeAllChildren();
        for (int i = 0; i < prototype.Sprites.Count; i++)
        {
            // first, check if the coloration is parented to another marking
            // and if so, just kinda sorta dont display it
            var skipdraw = false;
            if (prototype.ColorLinks?.Count > 0)
            {
                var name = prototype.Sprites[i] switch
                {
                    SpriteSpecifier.Rsi rsi => rsi.RsiState,
                    SpriteSpecifier.Texture texture => texture.TexturePath.Filename,
                    _ => null
                };

                if (name != null && prototype.ColorLinks.ContainsKey(name))
                {
                    // dont show it, cus its parented to another marking
                    skipdraw = true;
                }
            }
            var colorContainer = new BoxContainer
            {
                Orientation = LayoutOrientation.Vertical,
            };
            // so.
            // the color selector sliders decide which destination color to modify
            // based on its index in the list of color selectors.
            // this is a problem if we, say, want to *not* show a certain slider
            // cus then it'll modify the wrong color, unless the color happened to
            // be in index 0.
            if (!skipdraw)
                CMarkingColors.AddChild(colorContainer);

            ColorSelectorSliders colorSelector = new ColorSelectorSliders();
            colorSelector.IsAlphaVisible = true;

            colorContainer.AddChild(new Label { Text = $"{stateNames[i]} color:" });
            colorContainer.AddChild(colorSelector);

            var listing = _currentMarkings.Markings[_selectedMarkingCategory];

            var color = listing[listing.Count - 1 - item.ItemIndex].MarkingColors[i];
            var currentColor = new Color(
                color.RByte,
                color.GByte,
                color.BByte,
                color.AByte
            );
            colorSelector.Color = currentColor;
            _currentMarkingColors.Add(currentColor);
            var currentGlow = i < marking.MarkingGlow.Count ? marking.MarkingGlow[i] : 0f;
            _currentMarkingGlow.Add(Math.Clamp(currentGlow, 0f, 1f));
            var colorIndex = _currentMarkingColors.Count - 1;

            Action<Color> colorChanged = _ =>
            {
                _currentMarkingColors[colorIndex] = colorSelector.Color;

                ColorChanged(colorIndex);
            };
            colorSelector.OnColorChanged += colorChanged;

            if (skipdraw)
                continue;

            var glowRow = new BoxContainer
            {
                Orientation = LayoutOrientation.Horizontal,
                SeparationOverride = 8,
            };
            var glowLabel = new Label
            {
                Text = Loc.GetString("marking-glow-label"),
            };
            var glowSlider = new Slider
            {
                HorizontalExpand = true,
                MinValue = 0f,
                MaxValue = 1f,
                Rounded = false,
            };
            // Coyote Start
            var glowValueBox = new SpinBox
            {
                MinSize = new Vector2(56f, 0f),
                IsValid = value => value is >= 0 and <= 100,
            };
            glowValueBox.InitDefaultButtons();

            var settingGlowFromInput = false;
            var settingGlowFromSlider = false;
            var initialGlow = Math.Clamp(_currentMarkingGlow[colorIndex], 0f, 1f);
            glowSlider.SetValueWithoutEvent(initialGlow);
            glowValueBox.Value = (int)MathF.Round(initialGlow * 100f);

            glowSlider.OnValueChanged += _ =>
            {
                if (settingGlowFromInput)
                    return;

                settingGlowFromSlider = true;
                var normalizedGlow = Math.Clamp(glowSlider.Value, 0f, 1f);
                _currentMarkingGlow[colorIndex] = normalizedGlow;
                glowValueBox.Value = (int)MathF.Round(normalizedGlow * 100f);
                GlowChanged(colorIndex);
                settingGlowFromSlider = false;
            };

            glowValueBox.ValueChanged += _ =>
            {
                if (settingGlowFromSlider)
                    return;

                settingGlowFromInput = true;
                var clampedPercent = Math.Clamp(glowValueBox.Value, 0, 100);
                var normalizedGlow = clampedPercent / 100f;
                _currentMarkingGlow[colorIndex] = normalizedGlow;
                glowSlider.SetValueWithoutEvent(normalizedGlow);
                GlowChanged(colorIndex);
                settingGlowFromInput = false;
            };
            // Coyote End

            glowRow.AddChild(glowLabel);
            glowRow.AddChild(glowSlider);
            glowRow.AddChild(glowValueBox);
            colorContainer.AddChild(glowRow);
        }

        CustomNameTextEdit.Text = marking.CustomName ?? "";

        // Coyote Start
        _currentMarkingScale = marking.MarkingScale;
        _currentMarkingOffsetX = marking.MarkingOffset.X;
        _currentMarkingOffsetY = marking.MarkingOffset.Y;
        if (_selectedMarkingCategory == MarkingCategories.Genital)
        {
            var scaleButton = new Button
            {
                Text = Loc.GetString("marking-adjust-scale-text"),
            };
            var scaleBox = new BoxContainer
            {
                Orientation = LayoutOrientation.Vertical,
                Visible = false,
            };
            var scaleRow = new BoxContainer
            {
                Orientation = LayoutOrientation.Horizontal,
                SeparationOverride = 8,
            };
            var offsetXRow = new BoxContainer
            {
                Orientation = LayoutOrientation.Horizontal,
                SeparationOverride = 8,
            };
            var offsetYRow = new BoxContainer
            {
                Orientation = LayoutOrientation.Horizontal,
                SeparationOverride = 8,
            };
            var scaleLabel = new Label
            {
                Text = Loc.GetString("marking-scale-label"),
            };
            var scaleSlider = new Slider
            {
                HorizontalExpand = true,
                MinValue = 0.25f,
                MaxValue = 3.0f,
                Rounded = false,
            };
            var offsetXSlider = new Slider
            {
                HorizontalExpand = true,
                MinValue = -1.0f,
                MaxValue = 1.0f,
                Rounded = false,
            };
            var offsetYSlider = new Slider
            {
                HorizontalExpand = true,
                MinValue = -1.0f,
                MaxValue = 1.0f,
                Rounded = false,
            };
            var scaleValueBox = new SpinBox
            {
                MinSize = new Vector2(56f, 0f),
                IsValid = value => value is >= 25 and <= 300,
            };
            var offsetXValueBox = new SpinBox
            {
                MinSize = new Vector2(56f, 0f),
                IsValid = value => value is >= -100 and <= 100,
            };
            var offsetYValueBox = new SpinBox
            {
                MinSize = new Vector2(56f, 0f),
                IsValid = value => value is >= -100 and <= 100,
            };
            scaleValueBox.InitDefaultButtons();
            offsetXValueBox.InitDefaultButtons();
            offsetYValueBox.InitDefaultButtons();

            var settingScaleFromInput = false;
            var settingScaleFromSlider = false;
            var initialScale = Math.Clamp(_currentMarkingScale, 0.25f, 3.0f);
            scaleSlider.SetValueWithoutEvent(initialScale);
            scaleValueBox.Value = (int)MathF.Round(initialScale * 100f);

            var settingOffsetFromInput = false;
            var settingOffsetFromSlider = false;

            var initialOffsetX = Math.Clamp(_currentMarkingOffsetX, -1.0f, 1.0f);
            var initialOffsetY = Math.Clamp(_currentMarkingOffsetY, -1.0f, 1.0f);

            offsetXSlider.SetValueWithoutEvent(initialOffsetX);
            offsetYSlider.SetValueWithoutEvent(initialOffsetY);

            offsetXValueBox.Value = (int)MathF.Round(initialOffsetX * 100f);
            offsetYValueBox.Value = (int)MathF.Round(initialOffsetY * 100f);

            scaleSlider.OnValueChanged += _ =>
            {
                if (settingScaleFromInput)
                    return;

                settingScaleFromSlider = true;
                _currentMarkingScale = Math.Clamp(scaleSlider.Value, 0.25f, 3.0f);
                scaleValueBox.Value = (int)MathF.Round(_currentMarkingScale * 100f);
                ScaleChanged();
                settingScaleFromSlider = false;
            };

            scaleValueBox.ValueChanged += _ =>
            {
                if (settingScaleFromSlider)
                    return;

                settingScaleFromInput = true;
                var clampedPercent = Math.Clamp(scaleValueBox.Value, 25, 300);
                _currentMarkingScale = clampedPercent / 100f;
                scaleSlider.SetValueWithoutEvent(_currentMarkingScale);
                ScaleChanged();
                settingScaleFromInput = false;
            };

            void UpdateOffsetsFromInputs()
            {
                if (settingOffsetFromInput)
                    return;

                settingOffsetFromSlider = true;
                _currentMarkingOffsetX = Math.Clamp(offsetXSlider.Value, -1.0f, 1.0f);
                _currentMarkingOffsetY = Math.Clamp(offsetYSlider.Value, -1.0f, 1.0f);

                offsetXValueBox.Value = (int)MathF.Round(_currentMarkingOffsetX * 100f);
                offsetYValueBox.Value = (int)MathF.Round(_currentMarkingOffsetY * 100f);

                OffsetChanged();
                settingOffsetFromSlider = false;
            }

            void UpdateOffsetsFromBoxes()
            {
                if (settingOffsetFromSlider)
                    return;

                settingOffsetFromInput = true;

                _currentMarkingOffsetX = Math.Clamp(offsetXValueBox.Value, -100, 100) / 100f;
                _currentMarkingOffsetY = Math.Clamp(offsetYValueBox.Value, -100, 100) / 100f;

                offsetXSlider.SetValueWithoutEvent(_currentMarkingOffsetX);
                offsetYSlider.SetValueWithoutEvent(_currentMarkingOffsetY);

                OffsetChanged();
                settingOffsetFromInput = false;
            }

            offsetXSlider.OnValueChanged += _ => UpdateOffsetsFromInputs();
            offsetYSlider.OnValueChanged += _ => UpdateOffsetsFromInputs();

            offsetXValueBox.ValueChanged += _ => UpdateOffsetsFromBoxes();
            offsetYValueBox.ValueChanged += _ => UpdateOffsetsFromBoxes();

            scaleButton.OnPressed += _ =>
            {
                scaleBox.Visible = !scaleBox.Visible;
            };

            scaleRow.AddChild(scaleLabel);
            scaleRow.AddChild(scaleSlider);
            scaleRow.AddChild(scaleValueBox);
            offsetXRow.AddChild(new Label { Text = Loc.GetString("marking-offset-x-label") });
            offsetXRow.AddChild(offsetXSlider);
            offsetXRow.AddChild(offsetXValueBox);
            offsetYRow.AddChild(new Label { Text = Loc.GetString("marking-offset-y-label") });
            offsetYRow.AddChild(offsetYSlider);
            offsetYRow.AddChild(offsetYValueBox);

            scaleBox.AddChild(scaleRow);
            scaleBox.AddChild(offsetXRow);
            scaleBox.AddChild(offsetYRow);
            CMarkingColors.AddChild(scaleButton);
            CMarkingColors.AddChild(scaleBox);
        }
        // Coyote End
        StartVisibleToggle.Pressed = marking.ShowAtStart;
        CanPutOnToggle.Pressed = marking.CanToggleVisible;
        CanPutOnByOtherToggle.Pressed = marking.OtherCanToggleVisible;
        HideTogglePopupToggle.Pressed = marking.HideTogglePopup;
        PutOnTextEdit.Text = marking.PutOnVerb ?? Loc.GetString("marking-toggle-self-default-verb-on");
        TakeOffTextEdit.Text = marking.TakeOffVerb ?? Loc.GetString("marking-toggle-self-default-verb-off");
        PutOnOtherTextEdit.Text = marking.PutOnVerb2p ?? Loc.GetString("marking-toggle-other-default-verb-on");
        TakeOffOtherTextEdit.Text = marking.TakeOffVerb2p ?? Loc.GetString("marking-toggle-other-default-verb-off");

        MarkingData.Visible = true;
        CMarkingColors.Visible = true;
        SampleButton.Visible = true;
        SetCheckboxVisibility();
    }

    private void OnChangedLegStyle(OptionButton.ItemSelectedEventArgs legs)
    {
        CMarkingLegStyle.SelectId(legs.Id);
        CurrentLegStyle = (HumanoidLegStyle)legs.Id;
        OnLegStyleChanged?.Invoke(CurrentLegStyle);
    }

    private void SetCheckboxVisibility()
    {
        var togglePopupVisible = CanPutOnToggle.Pressed || CanPutOnByOtherToggle.Pressed;

        if (CanPutOnToggle.Pressed)
        {
            PutOnTextEdit.Visible = true;
            TakeOffTextEdit.Visible = true;
            PutOnTextEditLabel.Visible = true;
            TakeOffTextEditLabel.Visible = true;
        }
        else
        {
            PutOnTextEdit.Visible = false;
            TakeOffTextEdit.Visible = false;
            PutOnTextEditLabel.Visible = false;
            TakeOffTextEditLabel.Visible = false;
        }
        if (CanPutOnByOtherToggle.Pressed)
        {
            PutOnOtherTextEdit.Visible = true;
            TakeOffOtherTextEdit.Visible = true;
            PutOnOtherTextEditLabel.Visible = true;
            TakeOffOtherTextEditLabel.Visible = true;
        }
        else
        {
            PutOnOtherTextEdit.Visible = false;
            TakeOffOtherTextEdit.Visible = false;
            PutOnOtherTextEditLabel.Visible = false;
            TakeOffOtherTextEditLabel.Visible = false;
        }

        HideTogglePopupLabel.Visible = togglePopupVisible;
        HideTogglePopupToggle.Visible = togglePopupVisible;
    }

    private void ColorChanged(int colorIndex)
    {
        if (_selectedMarking is null) return;
        var markingPrototype = (MarkingPrototype)_selectedMarking.Metadata!;
        int markingIndex = _currentMarkings.FindIndexOf(_selectedMarkingCategory, markingPrototype.ID);

        if (markingIndex < 0) return;

        _selectedMarking.IconModulate = _currentMarkingColors[colorIndex];

        var marking = new Marking(_currentMarkings.Markings[_selectedMarkingCategory][markingIndex]);
        marking.SetColor(colorIndex, _currentMarkingColors[colorIndex]);
        _currentMarkings.Replace(_selectedMarkingCategory, markingIndex, marking);

        OnMarkingDataChanged?.Invoke(_currentMarkings);
    }

    private void GlowChanged(int glowIndex)
    {
        if (_selectedMarking is null) return;
        var markingPrototype = (MarkingPrototype)_selectedMarking.Metadata!;
        int markingIndex = _currentMarkings.FindIndexOf(_selectedMarkingCategory, markingPrototype.ID);

        if (markingIndex < 0) return;

        var marking = new Marking(_currentMarkings.Markings[_selectedMarkingCategory][markingIndex]);
        marking.SetGlow(glowIndex, _currentMarkingGlow[glowIndex]);
        _currentMarkings.Replace(_selectedMarkingCategory, markingIndex, marking);

        OnMarkingDataChanged?.Invoke(_currentMarkings);
    }

    // Coyote Start
    private void ScaleChanged()
    {
        if (_selectedMarking is null) return;
        var markingPrototype = (MarkingPrototype)_selectedMarking.Metadata!;
        int markingIndex = _currentMarkings.FindIndexOf(_selectedMarkingCategory, markingPrototype.ID);

        if (markingIndex < 0) return;

        var marking = new Marking(_currentMarkings.Markings[_selectedMarkingCategory][markingIndex]);
        marking.SetScale(_currentMarkingScale);
        _currentMarkings.Replace(_selectedMarkingCategory, markingIndex, marking);

        OnMarkingDataChanged?.Invoke(_currentMarkings);
    }

    private void OffsetChanged()
    {
        if (_selectedMarking is null) return;
        var markingPrototype = (MarkingPrototype)_selectedMarking.Metadata!;
        int markingIndex = _currentMarkings.FindIndexOf(_selectedMarkingCategory, markingPrototype.ID);

        if (markingIndex < 0) return;

        var marking = new Marking(_currentMarkings.Markings[_selectedMarkingCategory][markingIndex]);
        marking.SetOffset(_currentMarkingOffsetX, _currentMarkingOffsetY);
        _currentMarkings.Replace(_selectedMarkingCategory, markingIndex, marking);

        OnMarkingDataChanged?.Invoke(_currentMarkings);
    }

    // Coyote End

    private void SetCanToggle(bool canToggle)
    {
        if (_selectedMarking is null) return;
        var markingPrototype = (MarkingPrototype)_selectedMarking.Metadata!;
        int markingIndex = _currentMarkings.FindIndexOf(_selectedMarkingCategory, markingPrototype.ID);

        if (markingIndex < 0) return;

        var marking = new Marking(_currentMarkings.Markings[_selectedMarkingCategory][markingIndex]);
        marking.CanToggleVisible = canToggle;
        _currentMarkings.Replace(_selectedMarkingCategory, markingIndex, marking);
        SetCheckboxVisibility();

        OnMarkingDataChanged?.Invoke(_currentMarkings);
    }

    private void SetOtherCanToggle(bool canToggle)
    {
        if (_selectedMarking is null) return;
        var markingPrototype = (MarkingPrototype)_selectedMarking.Metadata!;
        int markingIndex = _currentMarkings.FindIndexOf(_selectedMarkingCategory, markingPrototype.ID);

        if (markingIndex < 0) return;

        var marking = new Marking(_currentMarkings.Markings[_selectedMarkingCategory][markingIndex]);
        marking.OtherCanToggleVisible = canToggle;
        _currentMarkings.Replace(_selectedMarkingCategory, markingIndex, marking);
        SetCheckboxVisibility();

        OnMarkingDataChanged?.Invoke(_currentMarkings);
    }

    private void SetVisible(bool visible)
    {
        if (_selectedMarking is null) return;
        var markingPrototype = (MarkingPrototype)_selectedMarking.Metadata!;
        int markingIndex = _currentMarkings.FindIndexOf(_selectedMarkingCategory, markingPrototype.ID);

        if (markingIndex < 0) return;

        var marking = new Marking(_currentMarkings.Markings[_selectedMarkingCategory][markingIndex]);
        marking.ShowAtStart = visible;
        _currentMarkings.Replace(_selectedMarkingCategory, markingIndex, marking);

        OnMarkingDataChanged?.Invoke(_currentMarkings);
    }

    private void SetHideTogglePopup(bool hide)
    {
        if (_selectedMarking is null) return;
        var markingPrototype = (MarkingPrototype)_selectedMarking.Metadata!;
        int markingIndex = _currentMarkings.FindIndexOf(_selectedMarkingCategory, markingPrototype.ID);

        if (markingIndex < 0) return;

        var marking = new Marking(_currentMarkings.Markings[_selectedMarkingCategory][markingIndex]);
        marking.HideTogglePopup = hide;
        _currentMarkings.Replace(_selectedMarkingCategory, markingIndex, marking);

        OnMarkingDataChanged?.Invoke(_currentMarkings);
    }

    private void SetCustomText()
    {
        if (_selectedMarking is null) return;
        var markingPrototype = (MarkingPrototype)_selectedMarking.Metadata!;
        int markingIndex = _currentMarkings.FindIndexOf(_selectedMarkingCategory, markingPrototype.ID);

        if (markingIndex < 0) return;

        var marking = new Marking(_currentMarkings.Markings[_selectedMarkingCategory][markingIndex]);

        marking.CustomName = CustomNameTextEdit.Text;
        marking.PutOnVerb = PutOnTextEdit.Text;
        marking.PutOnVerb2p = PutOnOtherTextEdit.Text;
        marking.TakeOffVerb = TakeOffTextEdit.Text;
        marking.TakeOffVerb2p = TakeOffOtherTextEdit.Text;

        if (marking.HideTogglePopup)
        {
            SampleText.Text = Loc.GetString("marking-toggle-popup-hidden-sample");
        }
        else
        {
            SampleText.Text = GetSampleText((string.IsNullOrEmpty(marking.CustomName) ? markingPrototype.ID : marking.CustomName),
            (string.IsNullOrEmpty(marking.PutOnVerb) ? Loc.GetString("marking-toggle-self-default-verb-on") : marking.PutOnVerb),
            (string.IsNullOrEmpty(marking.PutOnVerb2p) ? Loc.GetString("marking-toggle-other-default-verb-on") : marking.PutOnVerb2p))
                + "\n" + GetSampleText((string.IsNullOrEmpty(marking.CustomName) ? markingPrototype.ID : marking.CustomName),
            (string.IsNullOrEmpty(marking.TakeOffVerb) ? Loc.GetString("marking-toggle-self-default-verb-off") : marking.TakeOffVerb),
            (string.IsNullOrEmpty(marking.TakeOffVerb2p) ? Loc.GetString("marking-toggle-other-default-verb-off") : marking.TakeOffVerb2p));
        }

        _currentMarkings.Replace(_selectedMarkingCategory, markingIndex, marking);

        OnMarkingDataChanged?.Invoke(_currentMarkings);
    }

    private void ToggleSample()
    {
        if (SampleBox.Visible)
        {
            SampleBox.Visible = false;
            SampleButton.Text = Loc.GetString("marking-show-sample-text");
        }
        else
        {
            SetCustomText();
            SampleBox.Visible = true;
            SampleButton.Text = Loc.GetString("marking-hide-sample-text");
        }
    }

    private string GetSampleText(string name, string verb, string verb2p)
    {
        return Loc.GetString("marking-toggle-self-start",
            ("marking-name", name),
            ("verb", verb))
            + "\n" + Loc.GetString("marking-toggle-self",
            ("marking-name", name),
            ("verb", verb))
            + "\n" + Loc.GetString("marking-toggle-other-start",
            ("marking-name", name),
            ("verb", verb))
            + "\n" + Loc.GetString("marking-toggle-other",
            ("marking-name", name),
            ("verb", verb))
            + "\n" + Loc.GetString("marking-toggle-by-other-start",
            ("other", "Someone"),
            ("marking-name", name),
            ("verb", verb))
            + "\n" + Loc.GetString("marking-toggle-by-other",
            ("other", "Someone"),
            ("marking-name", name),
            ("verb", verb2p));
    }

    private void MarkingAdd()
    {
        if (_selectedUnusedMarking is null) return;

        if (_currentMarkings.PointsLeft(_selectedMarkingCategory) == 0 && !Forced)
        {
            return;
        }

        var marking = (MarkingPrototype)_selectedUnusedMarking.Metadata!;
        var markingObject = marking.AsMarking();

        // We need add hair markings in cloned set manually because _currentMarkings doesn't have it
        var markingSet = new MarkingSet(_currentMarkings);
        if (HairMarking != null)
        {
            markingSet.AddBack(MarkingCategories.Hair, HairMarking);
        }
        if (FacialHairMarking != null)
        {
            markingSet.AddBack(MarkingCategories.FacialHair, FacialHairMarking);
        }

        if (!_markingManager.MustMatchSkin(_currentSpecies, marking.BodyPart, out var _, _prototypeManager))
        {
            // Do default coloring
            var colors = MarkingColoring.GetMarkingLayerColors(
                marking,
                CurrentSkinColor,
                CurrentEyeColor,
                markingSet
            );
            for (var i = 0; i < colors.Count; i++)
            {
                markingObject.SetColor(i, colors[i]);
            }
        }
        else
        {
            // Color everything in skin color
            for (var i = 0; i < marking.Sprites.Count; i++)
            {
                markingObject.SetColor(i, CurrentSkinColor);
            }
        }

        // Frontier: Color overwrite
        if (_markingManager.MustMatchColor(_currentSpecies, marking.BodyPart, out var _, _prototypeManager) is Color forcedColor)
        {
            // Color everything in forced color
            for (var i = 0; i < marking.Sprites.Count; i++)
            {
                markingObject.SetColor(i, forcedColor);
            }
        }
        // End Frontier

        markingObject.Forced = Forced;

        _currentMarkings.AddBack(_selectedMarkingCategory, markingObject);

        UpdatePoints();

        CMarkingsUnused.Remove(_selectedUnusedMarking);
        var item = new ItemList.Item(CMarkingsUsed)
        {
            Text = Loc.GetString("marking-used", ("marking-name", $"{GetMarkingName(marking)}"), ("marking-category", Loc.GetString($"markings-category-{marking.MarkingCategory}"))),
            Icon = _sprite.Frame0(marking.Sprites[0]),
            Selectable = true,
            Metadata = marking,
        };
        CMarkingsUsed.Insert(0, item);
        // Select the newly added marking
        OnUsedMarkingSelected(new ItemList.ItemListSelectedEventArgs(0, CMarkingsUsed));

        _selectedUnusedMarking = null;
        OnMarkingAdded?.Invoke(_currentMarkings);
    }

    private void MarkingRemove()
    {
        if (_selectedMarking is null) return;

        var marking = (MarkingPrototype)_selectedMarking.Metadata!;

        _currentMarkings.Remove(_selectedMarkingCategory, marking.ID);

        UpdatePoints();

        CMarkingsUsed.Remove(_selectedMarking);

        if (marking.MarkingCategory == _selectedMarkingCategory)
        {
            var item = CMarkingsUnused.AddItem($"{GetMarkingName(marking)}", _sprite.Frame0(marking.Sprites[0]));
            item.Metadata = marking;
        }
        _selectedMarking = null;
        MarkingData.Visible = false;
        CMarkingColors.Visible = false;
        OnMarkingRemoved?.Invoke(_currentMarkings);
    }
}
