using System.Linq;
using Content.Client.Computer;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Shared.CCVar;
using Content.Shared.Parallax.Biomes;
using Content.Shared.Procedural;
using Content.Shared.Salvage;
using Content.Shared.Salvage.Expeditions;
using Content.Shared.Salvage.Expeditions.Modifiers;
using Content.Shared.Shuttles.BUIStates;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client.Salvage.UI;

/// <summary>
/// Generic window for offering multiple selections with a timer.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class OfferingWindowOption : PanelContainer
{
    private bool _claimed;
    private bool _pendingConfirmation;

    /// <summary>
    /// When true, the first click shows a confirmation warning; the second click fires ClaimPressed.
    /// </summary>
    public bool RequireConfirmation { get; set; }

    public string? Title
    {
        get => TitleStripe.Text;
        set => TitleStripe.Text = value;
    }

    public bool OpenContract
    {
        set
        {
            OpenContractStripe.Visible = value;
            if (value)
            {
                OpenContractLabel.Text = Loc.GetString("salvage-expedition-window-open-contract");
                OpenContractLabel.FontColorOverride = Color.FromHex("#FFF066");
            }
        }
    }

    public event Action<BaseButton.ButtonEventArgs>? ClaimPressed;

    public OfferingWindowOption()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        LayoutContainer.SetAnchorPreset(this, LayoutContainer.LayoutPreset.Wide);
        BigPanel.PanelOverride = new StyleBoxFlat(new Color(30, 30, 34));

        ConfirmationWarningLabel.SetMessage("Unconscious, or dead contractors will be returned to orbit at the end of the designated expedition time.", defaultColor: Color.FromHex("#FF8800"));
        ConfirmationClickLabel.Text = "Please click CLAIM again to confirm.";

        ClaimButton.OnPressed += args =>
        {
            if (RequireConfirmation && !_pendingConfirmation)
            {
                _pendingConfirmation = true;
                SetConfirmationVisible(true);
                // Undo the toggle so the button visually resets to unclaimed state.
                ClaimButton.Pressed = false;
                return;
            }
            _pendingConfirmation = false;
            SetConfirmationVisible(false);
            ClaimPressed?.Invoke(args);
        };
    }

    private void SetConfirmationVisible(bool visible)
    {
        ConfirmationWarningLabel.Visible = visible;
        ConfirmationClickLabel.Visible = visible;
    }

    public void AddContent(Control control)
    {
        ContentBox.AddChild(control);
    }

    public bool Disabled
    {
        get => ClaimButton.Disabled;
        set => ClaimButton.Disabled = value;
    }

    public bool Claimed
    {
        get => _claimed;
        set
        {
            if (_claimed == value)
                return;

            // Reset confirmation state whenever claimed status changes from outside.
            _pendingConfirmation = false;
            SetConfirmationVisible(false);

            _claimed = value;

            if (_claimed)
            {
                ClaimButton.AddStyleClass(StyleBase.ButtonCaution);
                ClaimButton.Text = Loc.GetString("offering-window-claimed");
            }
            else
            {
                ClaimButton.RemoveStyleClass(StyleBase.ButtonCaution);
                ClaimButton.Text = Loc.GetString("offering-window-claim");
            }
        }
    }
}
