- type: job
  id: Bailiff
  name: job-name-bailiff
  description: job-description-bailiff
  playTimeTracker: JobWarden
  requirements: # Coyote editted the playtime required for Sergeant
  - !type:OverallPlaytimeRequirement
    time: 108000
  - !type:DepartmentTimeRequirement
    department: Security
    time: 172800 # 48 hours
  startingGear: BailiffGear
  icon: JobIconBailiff
  supervisors: job-supervisors-sheriff
  weight: 150
  displayWeight: 60
  consoleAdjustable: false
  canBeAntag: false
  access: # Access was editted by Coyote
  - HeadOfSecurity
  - Command
  - Armory
  - Sergeant
  - Bailiff
  - Brigmedic
  accessGroups:
  - GeneralNfsdAccess
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, TrackingImplant ]
  - !type:GiveItemOnHolidaySpecial
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift
  - !type:AddRpiJobModifierSpecial
    modifiersToAdd:
    - rpiJobModifierBailiff
  - !type:AddComponentSpecial
    components:
    - type: CommandStaff
    - type: IsNfsd
      worth: 2


- type: startingGear
  id: BailiffGear
  equipment:
    pocket1: NFWeaponPistolUniversalNfsdLessLethal
    pocket2: HoloprojectorNfsd
  storage:
    back:
    - Flash
    - CSMagazinePistol40Overpressure # Coyote NFMagazineHighCapacityPistol35Overpressure < CSMagazinePistol40Overpressure
    - CSMagazinePistol40Rubber # Coyote NFMagazineHighCapacityPistol35Rubber < CSMagazinePistol40Rubber
    - BaseSecurityUplinkRadioOfficer
    - FrontierUplinkCoin5 # Coyote added 5 starting FUCs to Bailiff
    - ShipVoucherNfsdBailiff
    - RubberStampBailiff
    - EncryptionKeyCommand

- type: chameleonOutfit
  id: BailiffChameleonOutfit
  job: Bailiff
  hasMindShield: true
  equipment:
    head: ClothingHeadHatNfsdBeretBrown
    mask: ClothingMaskGasNfsd
    eyes: ClothingEyesGlassesNfsd
    outerClothing: ClothingOuterCoatNfsdFormal
    neck: ClothingNeckNfsdBadgeWarden
    belt: ClothingBeltNfsdFilled
    gloves: ClothingHandsGlovesCombatNfsdCream
    shoes: ClothingShoesBootsNfsdCreamFilled
